### ISSUE TITLE
i got minus at some metrics, 

### ISSUE THREAD

**Issue by ta2013** [Malfhas/caddy-grafana#2]
How to to fix those ?

![image](https://github.com/user-attachments/assets/29ce71d6-bada-426d-9863-bd91ade8bf11)

**Comment by findus** [comment]
I think the problem is when you restart caddy, the metrics reset to zero. If the current value is lower than the starting value due to caddy restarting and accumulated error/status codes havent reached the "old" high the numbers will be negative.

You can kinda make is less broken by switching from difference to range, values wont be negative anymore, but also not correct. For that, caddy would need persistent metrics.

![img](https://github.com/user-attachments/assets/1428d1f2-9ae9-4db8-b61d-c0fa7607711c)

**Comment by ta2013** [comment]
Thanks @findus 

It is not negative now.
